export const SEED_DOCUMENTS = [
  // ── Claim Forms ────────────────────────────────────────────────────────────
  {
    title: 'WCA Form 1 — Employee\'s Claim for Compensation',
    category: 'Form',
    filename: 'owc-wca-form-1.pdf',
    original_name: 'WCA-Form-1-Employee-Claim-for-Compensation.pdf',
    file_size: 214016,
  },
  {
    title: 'WCA Form 2 — Employer\'s Report of Work-Related Injury',
    category: 'Form',
    filename: 'owc-wca-form-2.pdf',
    original_name: 'WCA-Form-2-Employer-Report-of-Injury.pdf',
    file_size: 187392,
  },
  {
    title: 'WCA Form 3 — Medical Certificate & Assessment Report',
    category: 'Form',
    filename: 'owc-wca-form-3.pdf',
    original_name: 'WCA-Form-3-Medical-Certificate-Assessment.pdf',
    file_size: 229376,
  },
  {
    title: 'WCA Form 4 — Application for Rehabilitation Services',
    category: 'Form',
    filename: 'owc-wca-form-4.pdf',
    original_name: 'WCA-Form-4-Application-for-Rehabilitation.pdf',
    file_size: 196608,
  },
  {
    title: 'WCA Form 5 — Employer Registration Form',
    category: 'Form',
    filename: 'owc-wca-form-5.pdf',
    original_name: 'WCA-Form-5-Employer-Registration.pdf',
    file_size: 172032,
  },
  // ── Guides & Publications ──────────────────────────────────────────────────
  {
    title: 'Worker\'s Guide to Filing a Compensation Claim (2025)',
    category: 'Guide',
    filename: 'owc-workers-guide-2025.pdf',
    original_name: 'OWC-Workers-Guide-to-Filing-a-Claim-2025.pdf',
    file_size: 1572864,
  },
  {
    title: 'Employer\'s Handbook on Workers Compensation Obligations (2025)',
    category: 'Guide',
    filename: 'owc-employer-handbook-2025.pdf',
    original_name: 'OWC-Employer-Handbook-2025.pdf',
    file_size: 2097152,
  },
  {
    title: 'Rehabilitation & Return-to-Work Guidelines 2024',
    category: 'Guide',
    filename: 'owc-rehab-guidelines-2024.pdf',
    original_name: 'OWC-Rehabilitation-Return-to-Work-Guidelines-2024.pdf',
    file_size: 1310720,
  },
  {
    title: 'Understanding Medical Benefits Under Workers Compensation',
    category: 'Guide',
    filename: 'owc-medical-benefits-guide.pdf',
    original_name: 'OWC-Understanding-Medical-Benefits-Guide.pdf',
    file_size: 983040,
  },
  // ── Reports & Statistics ───────────────────────────────────────────────────
  {
    title: 'OWC Annual Report 2025',
    category: 'Report',
    filename: 'owc-annual-report-2025.pdf',
    original_name: 'OWC-Annual-Report-2025.pdf',
    file_size: 5242880,
  },
  {
    title: 'OWC Statistical Bulletin Q4 2025',
    category: 'Report',
    filename: 'owc-statistical-bulletin-q4-2025.pdf',
    original_name: 'OWC-Statistical-Bulletin-Q4-2025.pdf',
    file_size: 2621440,
  },
  {
    title: 'OWC Annual Report 2024',
    category: 'Report',
    filename: 'owc-annual-report-2024.pdf',
    original_name: 'OWC-Annual-Report-2024.pdf',
    file_size: 4718592,
  },
  // ── Legislation & Regulations ──────────────────────────────────────────────
  {
    title: 'Workers\' Compensation Act 1978 (Consolidated 2023)',
    category: 'Regulation',
    filename: 'workers-compensation-act-1978-consolidated-2023.pdf',
    original_name: 'Workers-Compensation-Act-1978-Consolidated-2023.pdf',
    file_size: 3670016,
  },
  {
    title: 'Workers\' Compensation (Medical Fees) Regulation 2025',
    category: 'Regulation',
    filename: 'owc-medical-fees-regulation-2025.pdf',
    original_name: 'Workers-Compensation-Medical-Fees-Regulation-2025.pdf',
    file_size: 1048576,
  },
  {
    title: 'Workers\' Compensation (Claims Procedures) Regulation 2022',
    category: 'Regulation',
    filename: 'owc-claims-procedures-regulation-2022.pdf',
    original_name: 'Workers-Compensation-Claims-Procedures-Regulation-2022.pdf',
    file_size: 1310720,
  },
]

export const SEED_SERVICES = [
  {
    position: 1,
    tag: 'Claims',
    icon_name: 'FileText',
    title: 'Workers Compensation Claims',
    description: 'The OWC processes compensation claims for workers who sustain injuries, illnesses, or disabilities arising out of or in the course of their employment. Our case officers guide claimants through every step of the process.',
    who_eligible: 'Any worker employed under a contract of service or apprenticeship in Papua New Guinea who has suffered a work-related injury or occupational disease.',
    benefits: [
      'Medical expenses coverage from the date of injury',
      'Weekly earnings compensation during incapacity',
      'Lump-sum payment for permanent impairment',
      'Funeral expenses in case of fatality',
      'Dedicated case officer support throughout the claim',
    ],
  },
  {
    position: 2,
    tag: 'Employers',
    icon_name: 'Building2',
    title: 'Employer Registration & Compliance',
    description: "All employers in Papua New Guinea with one or more employees are legally required to register with the OWC and maintain valid workers compensation insurance. We assist employers in meeting their obligations under the Workers' Compensation Act 1978.",
    who_eligible: 'All employers including businesses, government agencies, NGOs, and sole traders who employ one or more workers under a contract of service.',
    benefits: [
      'Guided registration process with dedicated support',
      'Compliance certificate issued upon successful registration',
      'Access to employer training and awareness workshops',
      'Early notification of regulatory changes and updates',
      'Online self-service portal for policy renewals',
    ],
  },
  {
    position: 3,
    tag: 'Medical',
    icon_name: 'HeartPulse',
    title: 'Medical Treatment & Benefits',
    description: 'Injured workers are entitled to receive all necessary medical treatment for their work-related injury or disease. OWC coordinates with approved medical providers across PNG to ensure timely and appropriate care.',
    who_eligible: 'Workers with an accepted compensation claim who require medical treatment, specialist consultations, hospitalisation, physiotherapy, or prescribed medication.',
    benefits: [
      'Coverage at approved hospitals and clinics nationwide',
      'Specialist and allied health referrals',
      'Physiotherapy and rehabilitation services',
      'Prescribed medications and medical aids',
      'Medical travel allowance for remote workers',
    ],
  },
  {
    position: 4,
    tag: 'Rehabilitation',
    icon_name: 'Activity',
    title: 'Rehabilitation & Return to Work',
    description: "OWC's rehabilitation program is designed to help injured workers recover their capacity and return to safe and sustainable employment. We work with employers, medical providers, and workers to develop tailored return-to-work plans.",
    who_eligible: 'Workers with a workers compensation claim who have a permanent or partial incapacity and wish to return to work or retrain for new employment.',
    benefits: [
      'Personalised return-to-work planning',
      'Vocational retraining and skills assessment',
      'Workplace modification support for employers',
      'Ongoing monitoring and adjustment of the rehab plan',
      'Coordination with medical and allied health providers',
    ],
  },
  {
    position: 5,
    tag: 'Legal',
    icon_name: 'Scale',
    title: 'Dispute Resolution',
    description: 'Where a claim is disputed between a worker and employer or insurer, OWC provides a formal dispute resolution pathway. Our officers facilitate conciliation, and unresolved disputes are referred to the Workers Compensation Tribunal.',
    who_eligible: 'Workers or employers who have a disagreement regarding the acceptance, amount, or management of a workers compensation claim.',
    benefits: [
      'Free conciliation service for both parties',
      'Impartial case review by experienced officers',
      "Referral to the Workers' Compensation Tribunal if required",
      'Legal information and guidance on rights and obligations',
      'Timely resolution targets to minimise delays',
    ],
  },
  {
    position: 6,
    tag: 'Benefits',
    icon_name: 'Users',
    title: 'Death & Dependency Benefits',
    description: "When a worker dies as a result of a work-related injury or disease, their dependants are entitled to compensation under the Workers' Compensation Act. OWC provides compassionate support to families throughout the claims process.",
    who_eligible: 'Dependants of a deceased worker including spouse, children, and other financial dependants where death has been caused or contributed to by a work-related injury or occupational disease.',
    benefits: [
      'Lump-sum payment to eligible dependants',
      'Funeral expenses reimbursement',
      'Periodic payments for dependent children up to age 16',
      'Extended support for totally dependent surviving spouses',
      'Dedicated family liaison officer assigned to each case',
    ],
  },
  {
    position: 7,
    tag: 'Compliance',
    icon_name: 'ShieldCheck',
    title: 'Inspections & Enforcement',
    description: "OWC conducts workplace inspections and enforcement activities to ensure employers comply with the Workers' Compensation Act 1978. Non-compliant employers are subject to penalties and prosecution.",
    who_eligible: 'Applicable to all employers operating in Papua New Guinea. Workers may also report non-compliant employers confidentially to OWC.',
    benefits: [
      'Confidential reporting channel for non-compliance',
      'Workplace inspection and audit services',
      'Compliance improvement plans for first-time offenders',
      'Public register of compliant employers',
      'Enforcement action including infringement notices and prosecution',
    ],
  },
]

export const SEED_NEWS = [
  {
    slug: 'owc-launches-digital-claims-portal-2026',
    date: '17 March 2026',
    month: 'March',
    year: '2026',
    category: 'Announcement',
    title: 'OWC Launches Digital Claims Portal for 2026',
    excerpt: 'The Office of Workers Compensation has officially launched its new online claims lodgement portal, enabling injured workers across Papua New Guinea to submit and track compensation claims digitally.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    author: 'OWC Communications',
    read_time: '4 min read',
    body: [
      {
        heading: 'A New Era for Workers Compensation',
        text: 'The Office of Workers Compensation (OWC) is proud to announce the launch of its Digital Claims Portal. The portal allows workers to lodge new claims, upload supporting documents, and track the progress of their case in real time.',
      },
      {
        heading: 'Key Features of the Portal',
        text: 'The portal includes a guided claims lodgement wizard, secure document upload, email and SMS status notifications, and a case history dashboard. The interface has been optimised for low-bandwidth connections common in provincial PNG.',
      },
      {
        heading: 'Support Remains Available',
        text: 'Workers who prefer in-person assistance can continue to visit any OWC provincial office. Toll-free assistance is also available on 180 1100, Monday to Friday, 8:00 AM to 4:00 PM.',
      },
    ],
  },
  {
    slug: 'owc-annual-report-2025',
    date: '28 February 2026',
    month: 'February',
    year: '2026',
    category: 'Reports',
    title: 'OWC Annual Report 2025: K3.8 Million in Benefits Paid',
    excerpt: 'The OWC has released its Annual Report for the 2025 financial year, recording over K3.8 million in compensation benefits paid to injured workers and their families across Papua New Guinea.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    author: 'OWC Communications',
    read_time: '5 min read',
    body: [
      {
        heading: 'Record Benefits Disbursement',
        text: 'The 2025 Annual Report marks the highest level of compensation disbursement in OWC history, with K3.8 million paid out across 1,923 accepted claims. This represents a 12% increase on the previous year.',
      },
      {
        heading: 'Improved Processing Times',
        text: 'Average claim processing time fell from 74 days in 2024 to 61 days in 2025, driven by staff capacity building and the rollout of a new case management system. The target for 2026 is 45 days.',
      },
      {
        heading: 'Download the Report',
        text: 'The full Annual Report 2025 is available for download from the Resources section of this website. Printed copies are available at all OWC provincial offices.',
      },
    ],
  },
  {
    slug: 'employer-compliance-drive-highlands-2026',
    date: '10 January 2026',
    month: 'January',
    year: '2026',
    category: 'News',
    title: 'OWC Compliance Drive Reaches Highlands Region',
    excerpt: 'OWC inspectors have completed a major compliance campaign across the Highlands region, visiting over 140 employers in Western Highlands, Enga, and Southern Highlands provinces.',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80',
    author: 'OWC Communications',
    read_time: '3 min read',
    body: [
      {
        heading: 'Campaign Overview',
        text: 'Over a four-week period in December 2025, OWC inspection teams visited 143 employers across the Highlands region. Of those visited, 89 were fully compliant, 34 received improvement notices, and 20 were referred for enforcement action.',
      },
      {
        heading: 'Awareness Workshops Conducted',
        text: 'OWC facilitated six employer awareness workshops in Mt Hagen, Mendi, and Wabag, attended by a combined 310 employer representatives covering registration obligations, injury reporting, and worker rights.',
      },
      {
        heading: 'Ongoing Compliance Monitoring',
        text: 'Employers who received compliance improvement notices will be re-visited within 60 days. Registration is a legal requirement under the Workers Compensation Act 1978, and non-compliance can result in significant financial penalties.',
      },
    ],
  },
  {
    slug: 'medical-benefits-expanded-2025',
    date: '5 November 2025',
    month: 'November',
    year: '2025',
    category: 'Policy',
    title: 'Medical Benefits Extended Under Revised Compensation Schedule',
    excerpt: "The Workers' Compensation (Medical Fees) Regulation has been updated, expanding the range of covered treatments and increasing reimbursement rates for the first time since 2018.",
    image: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?w=800&q=80',
    author: 'OWC Communications',
    read_time: '3 min read',
    body: [
      {
        heading: 'What Has Changed',
        text: 'The revised Medical Fees Regulation, effective 1 November 2025, adds coverage for telehealth consultations, physiotherapy, occupational therapy, and mental health services directly related to workplace injuries.',
      },
      {
        heading: 'Mental Health Now Covered',
        text: 'Psychological treatment for work-related mental health conditions including trauma, anxiety, and depression arising from workplace incidents is now covered. Workers must obtain a referral from their treating medical officer.',
      },
      {
        heading: 'Accessing Updated Benefits',
        text: 'Workers with existing accepted claims who require newly covered services should contact their OWC case officer. New claimants lodging from 1 November 2025 will automatically be assessed under the updated schedule.',
      },
    ],
  },
  {
    slug: 'owc-national-labour-week-2025',
    date: '22 October 2025',
    month: 'October',
    year: '2025',
    category: 'Awareness',
    title: 'OWC Marks National Labour Week with Nationwide Outreach',
    excerpt: "As part of Papua New Guinea's National Labour Week celebrations, OWC conducted outreach programs in seven provinces, reaching over 2,000 workers and employers.",
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
    author: 'OWC Communications',
    read_time: '2 min read',
    body: [
      {
        heading: 'National Labour Week 2025',
        text: 'OWC deployed outreach teams to NCD, Lae, Mt Hagen, Goroka, Kokopo, Alotau, and Daru. Information booths, Q&A sessions, and free consultation services were provided to workers and employer representatives.',
      },
      {
        heading: 'Key Messages',
        text: 'Outreach teams focused on three key messages: every employer must register, every injured worker has the right to claim, and OWC services are free. Thousands of brochures and claim forms were distributed.',
      },
    ],
  },
]

export const SEED_EVENTS = [
  {
    title: 'Employer Registration Workshop - Port Moresby',
    description: "A practical half-day workshop guiding employers through the OWC registration process, insurance requirements, and their obligations under the Workers' Compensation Act 1978.",
    event_date: '2026-04-10',
    event_time: '08:30 - 12:30',
    location: 'OWC Head Office, Wards Road, Port Moresby, NCD',
    category: 'Workshop',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    title: 'Claims Processing Training - Lae',
    description: 'An in-depth training session for HR officers, safety managers, and employer representatives on how to correctly document, report, and manage workers compensation claims.',
    event_date: '2026-04-24',
    event_time: '09:00 - 16:00',
    location: 'Lae City Hall, Independence Drive, Lae, Morobe Province',
    category: 'Training',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
  },
  {
    title: 'Workers Rights Awareness Day - Mt Hagen',
    description: 'A free public awareness event for workers across the Highlands region. OWC case officers will be on hand to answer questions and assist with claim lodgement enquiries.',
    event_date: '2026-05-15',
    event_time: '08:00 - 15:00',
    location: 'Mt Hagen Cultural Centre, Western Highlands Province',
    category: 'Awareness',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
  },
  {
    title: 'Provincial Outreach Program - Western Province',
    description: 'OWC mobile outreach teams will travel to Daru and surrounding communities to provide face-to-face services including claim lodgement, employer registration, and general advisory services.',
    event_date: '2026-05-28',
    event_time: '08:00 - 17:00',
    location: 'Daru District Office, Western Province',
    category: 'Outreach',
    image: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&q=80',
  },
  {
    title: 'Annual Employers Conference 2026',
    description: "OWC's flagship annual event bringing together employers, insurers, legal practitioners, and government stakeholders to discuss the state of workers compensation in PNG and best practices for workplace safety.",
    event_date: '2026-06-19',
    event_time: '07:30 - 17:00',
    location: 'Stanley Hotel & Suites, Waigani, NCD',
    category: 'Conference',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
  },
  {
    title: 'Rehabilitation & Return-to-Work Forum',
    description: 'A collaborative forum for employers, medical providers, and OWC rehabilitation coordinators to align on best-practice return-to-work strategies. Case studies, panel discussions, and interactive workshops.',
    event_date: '2026-07-09',
    event_time: '09:00 - 15:00',
    location: 'APEC Haus, Port Moresby, NCD',
    category: 'Workshop',
    image: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
  },
]
