export const SEED_DOCUMENTS = [
  // ── Court Forms ────────────────────────────────────────────────────────────
  {
    title: 'Writ of Summons — National Court',
    category: 'Form',
    filename: 'njss-writ-of-summons.pdf',
    original_name: 'National-Court-Writ-of-Summons.pdf',
    file_size: 214016,
  },
  {
    title: 'Originating Summons — National Court',
    category: 'Form',
    filename: 'njss-originating-summons.pdf',
    original_name: 'National-Court-Originating-Summons.pdf',
    file_size: 187392,
  },
  {
    title: 'Notice of Appeal — Supreme Court',
    category: 'Form',
    filename: 'njss-notice-of-appeal.pdf',
    original_name: 'Supreme-Court-Notice-of-Appeal.pdf',
    file_size: 229376,
  },
  {
    title: 'Notice of Motion',
    category: 'Form',
    filename: 'njss-notice-of-motion.pdf',
    original_name: 'Notice-of-Motion.pdf',
    file_size: 196608,
  },
  {
    title: 'Standard Affidavit Form',
    category: 'Form',
    filename: 'njss-affidavit-form.pdf',
    original_name: 'Standard-Affidavit-Form.pdf',
    file_size: 172032,
  },
  {
    title: 'Application for Judicial Review',
    category: 'Form',
    filename: 'njss-judicial-review-application.pdf',
    original_name: 'Application-for-Judicial-Review.pdf',
    file_size: 203776,
  },
  // ── Guides & Publications ──────────────────────────────────────────────────
  {
    title: 'Guide to Filing in the National Court (2025)',
    category: 'Guide',
    filename: 'njss-national-court-filing-guide-2025.pdf',
    original_name: 'NJSS-Guide-to-Filing-in-the-National-Court-2025.pdf',
    file_size: 1572864,
  },
  {
    title: 'Supreme Court Practice Directions (2024)',
    category: 'Guide',
    filename: 'njss-supreme-court-practice-directions-2024.pdf',
    original_name: 'Supreme-Court-Practice-Directions-2024.pdf',
    file_size: 2097152,
  },
  {
    title: 'Self-Represented Litigants Handbook',
    category: 'Guide',
    filename: 'njss-self-represented-litigants-handbook.pdf',
    original_name: 'NJSS-Self-Represented-Litigants-Handbook.pdf',
    file_size: 1310720,
  },
  {
    title: 'Court Library Membership Guide',
    category: 'Guide',
    filename: 'njss-court-library-membership-guide.pdf',
    original_name: 'NJSS-Court-Library-Membership-Guide.pdf',
    file_size: 983040,
  },
  // ── Reports & Statistics ───────────────────────────────────────────────────
  {
    title: 'Annual Judges Report 2025',
    category: 'Report',
    filename: 'njss-annual-judges-report-2025.pdf',
    original_name: 'Annual-Judges-Report-2025.pdf',
    file_size: 5242880,
  },
  {
    title: 'Annual Judges Report 2024',
    category: 'Report',
    filename: 'njss-annual-judges-report-2024.pdf',
    original_name: 'Annual-Judges-Report-2024.pdf',
    file_size: 4718592,
  },
  // ── Legislation & Rules ────────────────────────────────────────────────────
  {
    title: 'Supreme Court Act (Chapter 37)',
    category: 'Regulation',
    filename: 'supreme-court-act-chapter-37.pdf',
    original_name: 'Supreme-Court-Act-Chapter-37.pdf',
    file_size: 3670016,
  },
  {
    title: 'National Court Act (Chapter 38)',
    category: 'Regulation',
    filename: 'national-court-act-chapter-38.pdf',
    original_name: 'National-Court-Act-Chapter-38.pdf',
    file_size: 1048576,
  },
  {
    title: 'Supreme Court Rules',
    category: 'Regulation',
    filename: 'supreme-court-rules.pdf',
    original_name: 'Supreme-Court-Rules.pdf',
    file_size: 1310720,
  },
  {
    title: 'National Court Rules',
    category: 'Regulation',
    filename: 'national-court-rules.pdf',
    original_name: 'National-Court-Rules.pdf',
    file_size: 1572864,
  },
]

export const SEED_SERVICES = [
  {
    position: 1,
    tag: 'Supreme Court',
    icon_name: 'Scale',
    title: 'Supreme Court',
    description: 'The Supreme Court is the highest court in Papua New Guinea, exercising original and appellate jurisdiction. It hears constitutional matters, appeals from the National Court, and other matters assigned by law.',
    who_eligible: 'Parties wishing to appeal a National Court decision, bring constitutional references, or commence proceedings invoking the original jurisdiction of the Supreme Court.',
    benefits: [
      'Final appellate jurisdiction over all courts in Papua New Guinea',
      'Original jurisdiction in constitutional matters and references',
      'Full bench sittings for significant constitutional and legal questions',
      'Summary determination of appeals and applications',
      'Daily court diary published for all scheduled hearings',
    ],
  },
  {
    position: 2,
    tag: 'National Court',
    icon_name: 'Building2',
    title: 'National Court',
    description: 'The National Court is the principal trial court of Papua New Guinea with unlimited jurisdiction in civil and criminal matters. It operates through registries in all major provinces and conducts circuit sittings in remote areas.',
    who_eligible: 'Any person or entity with a civil or criminal matter exceeding the jurisdiction of lower courts, or matters specifically assigned to the National Court by law.',
    benefits: [
      'Civil Division — contract, property, human rights, commercial disputes',
      'Criminal Division — serious criminal trials committed from District Courts',
      'Equity Division — commercial, appeals, and human rights applications',
      'Alternative Dispute Resolution (ADR) services',
      'Provincial registries and circuit sittings across all 22 provinces',
    ],
  },
  {
    position: 3,
    tag: 'Registry',
    icon_name: 'FileText',
    title: 'Court Registry Services',
    description: 'The court registry provides filing, case management, and document services for both the Supreme Court and National Court. Registries operate in Waigani and all provincial centres.',
    who_eligible: 'Legal practitioners, self-represented litigants, and members of the public requiring court filing, document retrieval, or certified copies of court records.',
    benefits: [
      'Filing of originating process and interlocutory applications',
      'Issuance of court seals, certified copies, and court orders',
      'Case listing and scheduling services',
      'Online filing available through the E-Judiciary portal',
      'Fee waiver applications for financially disadvantaged litigants',
    ],
  },
  {
    position: 4,
    tag: 'Sheriff',
    icon_name: 'Shield',
    title: 'Sheriff Services',
    description: 'The Sheriff\'s office is responsible for enforcement of court orders, service of court documents, and execution of writs throughout Papua New Guinea.',
    who_eligible: 'Judgment creditors requiring enforcement of court orders, parties requiring formal service of court documents, and litigants needing execution of writs.',
    benefits: [
      'Enforcement of civil judgments and court orders',
      'Service of originating process and other court documents',
      'Execution of writs of levy of property',
      'Seizure and sale of property under court order',
      'Assistance with evictions pursuant to court orders',
    ],
  },
  {
    position: 5,
    tag: 'Library',
    icon_name: 'BookOpen',
    title: 'Court Library',
    description: 'The Court Library provides comprehensive legal research facilities, publications, and databases to support legal practitioners, judicial officers, academics, and the public.',
    who_eligible: 'Judicial officers, legal practitioners, law students, academics, and members of the public seeking access to legal research materials and publications.',
    benefits: [
      'Extensive collection of PNG and comparative law publications',
      'Access to online legal research databases and tools',
      'Branch libraries at provincial registries',
      'Library membership available to legal practitioners and institutions',
      'Legal research assistance from qualified library staff',
    ],
  },
  {
    position: 6,
    tag: 'Interpreting',
    icon_name: 'Globe',
    title: 'Interpreting Services',
    description: 'The court interpreting service provides accredited interpreters for court proceedings to ensure all parties understand and can participate in proceedings regardless of language.',
    who_eligible: 'Parties, witnesses, and accused persons in court proceedings who require interpretation services in Tok Pisin, Motu, or other PNG languages.',
    benefits: [
      'Accredited court interpreters for all major PNG languages',
      'Tok Pisin and Motu interpretation as standard',
      'Regional language interpreters available on request',
      'Interpretation services for pre-trial conferences and hearings',
      'Training and accreditation program for new court interpreters',
    ],
  },
  {
    position: 7,
    tag: 'Reporting',
    icon_name: 'Newspaper',
    title: 'Court Reporting Service',
    description: 'The court reporting service provides verbatim transcripts of court proceedings for use by parties, legal practitioners, and for appeal purposes.',
    who_eligible: 'Parties to proceedings who require a transcript, legal practitioners preparing appeals, and judicial officers requiring records of proceedings.',
    benefits: [
      'Verbatim transcripts of court hearings and judgments',
      'Digital audio recording of all court proceedings',
      'Expedited transcript production for urgent appeal matters',
      'Archival and retrieval of historical court records',
      'Certified transcripts available for use in evidence',
    ],
  },
]

export const SEED_NEWS = [
  {
    slug: 'njss-e-judiciary-portal-launch-2026',
    date: '17 March 2026',
    month: 'March',
    year: '2026',
    category: 'Announcement',
    title: 'NJSS Launches E-Judiciary Portal for Online Court Filings',
    excerpt: 'The National Judicial Staff Service has launched its new E-Judiciary portal, enabling legal practitioners and litigants to file court documents, access daily court diaries, and track matters online.',
    image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&q=80',
    author: 'NJSS Communications',
    read_time: '4 min read',
    body: [
      {
        heading: 'A New Era for Court Administration',
        text: 'The National Judicial Staff Service (NJSS) is proud to announce the launch of the E-Judiciary portal. Legal practitioners can now lodge documents, access the daily court diary, and track the progress of their matters online without visiting the registry in person.',
      },
      {
        heading: 'Key Features of the Portal',
        text: 'The portal includes online document filing, court diary access, case status tracking, and electronic payment of court fees. The interface has been optimised for use on mobile devices and low-bandwidth connections common in provincial PNG.',
      },
      {
        heading: 'Registry Services Remain Available',
        text: 'All court registries remain open for in-person filing. Litigants who prefer to file in person can continue to do so at the Waigani Court Complex or any provincial registry Monday to Friday, 8:00 AM to 4:00 PM.',
      },
    ],
  },
  {
    slug: 'annual-judges-report-2025',
    date: '28 February 2026',
    month: 'February',
    year: '2026',
    category: 'Reports',
    title: 'Annual Judges Report 2025 Released',
    excerpt: 'The Supreme Court and National Court of Papua New Guinea have released the Annual Judges Report for 2025, highlighting key judicial outcomes, case statistics, and administrative achievements.',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
    author: 'NJSS Communications',
    read_time: '5 min read',
    body: [
      {
        heading: 'Highlights from the 2025 Report',
        text: 'The 2025 Annual Judges Report records significant progress in case management, reduced backlog in the National Court civil division, and the successful rollout of digital case management tools across provincial registries.',
      },
      {
        heading: 'Provincial Registry Improvements',
        text: 'New registries were upgraded in Kokopo and Alotau, with improved facilities for litigants and legal practitioners. Circuit court sittings in remote provinces increased by 15% compared to 2024.',
      },
      {
        heading: 'Download the Report',
        text: 'The full Annual Judges Report 2025 is available for download from the Resources section of this website. Printed copies are available at all court registries.',
      },
    ],
  },
  {
    slug: 'waigani-court-complex-update-2026',
    date: '15 January 2026',
    month: 'January',
    year: '2026',
    category: 'Notice',
    title: 'Waigani Court Complex Expansion Update',
    excerpt: 'Construction works on the Waigani Court Complex expansion are progressing on schedule. Updated court room allocations and registry locations are now in effect.',
    image: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80',
    author: 'NJSS Communications',
    read_time: '3 min read',
    body: [
      {
        heading: 'Expansion Progress',
        text: 'The Waigani Court Complex expansion project is on track for completion in mid-2026. The new facilities will include four additional court rooms, upgraded registry facilities, and improved public access areas.',
      },
      {
        heading: 'Temporary Arrangements',
        text: 'During construction, certain court rooms have been temporarily relocated. Litigants and legal practitioners should check the daily court diary for current room allocations before attending court.',
      },
      {
        heading: 'Contact the Registry',
        text: 'For queries about court room allocations or registry locations during the construction period, contact the Waigani Registry on +675 325 7902 or email info@judiciary.gov.pg.',
      },
    ],
  },
  {
    slug: 'njss-tenders-board-notice-2025',
    date: '5 November 2025',
    month: 'November',
    year: '2025',
    category: 'Procurement',
    title: 'NJSS Tenders Board — Expression of Interest for IT Services',
    excerpt: 'The NJSS Tenders Board invites expressions of interest from qualified IT service providers for the supply and maintenance of court case management systems.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
    author: 'NJSS Tenders Board',
    read_time: '3 min read',
    body: [
      {
        heading: 'Scope of Services',
        text: 'The NJSS is seeking expressions of interest from qualified information technology service providers with experience in court management systems, database administration, and government IT infrastructure.',
      },
      {
        heading: 'Submission Requirements',
        text: 'Interested parties should submit company profiles, relevant experience, and technical capability statements to the NJSS Tenders Board by the closing date. Full tender documents will be issued to shortlisted respondents.',
      },
    ],
  },
  {
    slug: 'pngcje-judicial-training-2025',
    date: '22 October 2025',
    month: 'October',
    year: '2025',
    category: 'Training',
    title: 'PNG Centre for Judicial Excellence Holds Annual Training Program',
    excerpt: 'The PNG Centre for Judicial Excellence (PNGCJE) concluded its annual judicial education program, with judges and magistrates from across Papua New Guinea completing modules on evidence, sentencing, and human rights.',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
    author: 'NJSS Communications',
    read_time: '2 min read',
    body: [
      {
        heading: 'Annual Judicial Training',
        text: 'The PNGCJE delivered a week-long residential training program at Waigani attended by 42 judicial officers from the Supreme Court, National Court, and District Courts. Modules covered contemporary issues in evidence law, sentencing principles, and international human rights standards.',
      },
      {
        heading: 'International Faculty',
        text: 'The program featured guest faculty from the Federal Court of Australia and the Pacific Judicial Development Programme, bringing comparative perspectives on judicial practice to PNG judges.',
      },
    ],
  },
]

export const SEED_EVENTS = [
  {
    title: 'Judicial Education Workshop — Evidence Law',
    description: 'A full-day workshop for National Court judges and magistrates on contemporary evidence law issues, including electronic evidence, expert witnesses, and admissibility standards.',
    event_date: '2026-04-10',
    event_time: '08:30 - 16:30',
    location: 'PNG Centre for Judicial Excellence, Waigani, NCD',
    category: 'Training',
    image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&q=80',
  },
  {
    title: 'Provincial Registrars Conference 2026',
    description: 'Annual conference bringing together registrars from all provincial court registries to align on case management procedures, registry services, and the rollout of the E-Judiciary portal.',
    event_date: '2026-04-24',
    event_time: '09:00 - 16:00',
    location: 'Waigani Court Complex, Port Moresby, NCD',
    category: 'Conference',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
  },
  {
    title: 'Law Week Public Forum — Access to Justice',
    description: 'A free public forum as part of PNG Law Week, featuring judges, lawyers, and community leaders discussing access to justice, legal aid, and the role of the courts in Papua New Guinea.',
    event_date: '2026-05-15',
    event_time: '09:00 - 13:00',
    location: 'University of Papua New Guinea, Waigani, NCD',
    category: 'Awareness',
    image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800&q=80',
  },
  {
    title: 'NJSS Tenders Board — Procurement Training',
    description: 'A half-day procurement training workshop for NJSS staff on government procurement processes, tendering requirements, and compliance with the PFMA.',
    event_date: '2026-05-28',
    event_time: '08:00 - 12:00',
    location: 'NJSS Training Room, Waigani Court Complex, NCD',
    category: 'Training',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
  },
  {
    title: 'Supreme Court Annual Sitting — Kokopo',
    description: 'The Supreme Court will conduct its annual circuit sitting in Kokopo, East New Britain Province, hearing appeals and constitutional matters from the New Guinea Islands region.',
    event_date: '2026-06-19',
    event_time: '09:00 - 16:00',
    location: 'Kokopo National Court, East New Britain Province',
    category: 'Conference',
    image: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80',
  },
  {
    title: 'Court Library — Legal Research Seminar',
    description: 'A seminar for law students and junior lawyers on legal research skills, using the court library databases, and locating PNG case law and legislation.',
    event_date: '2026-07-09',
    event_time: '10:00 - 13:00',
    location: 'Court Library, Waigani Court Complex, NCD',
    category: 'Workshop',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
  },
]
